In [43]:
import torch
import numpy as np


tensor_pt = torch.randn(3, 4)
tensor_np = np.random.randn(3, 4)
print(tensor_pt)
print(tensor_np)

# 禁用科学模式，保留4为小数
torch.set_printoptions(precision=4, sci_mode=False)
np.set_printoptions(precision=4, suppress=True)

print(tensor_pt)
print(tensor_np)


tensor([[-0.5964, -1.1924,  0.2651,  0.8247],
        [-0.0318, -0.0435, -1.2811, -0.1063],
        [-2.1027,  0.2669,  0.4188,  0.3299]])
[[ 0.49671415 -0.1382643   0.64768854  1.52302986]
 [-0.23415337 -0.23413696  1.57921282  0.76743473]
 [-0.46947439  0.54256004 -0.46341769 -0.46572975]]
tensor([[-0.5964, -1.1924,  0.2651,  0.8247],
        [-0.0318, -0.0435, -1.2811, -0.1063],
        [-2.1027,  0.2669,  0.4188,  0.3299]])
[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]]
